#!/usr/bin/env python3
"""Long REPL sessions reuse dead tail storage without moving surviving values."""
from pathlib import Path
import argparse
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--frontend', type=Path)
args = parser.parse_args()
fronts = [[ROOT / 'build/cool-compiler'],
          [ROOT / 'build/coolc', '--run', ROOT / 'build/language.BIN']]
if args.frontend:
    fronts.append([args.frontend.resolve()])


def check(front, name, source, output, errors=()):
    result = subprocess.run([*front, 'repl-quiet'], input=source + '\n:quit\n',
                            text=True, capture_output=True, timeout=120)
    assert result.returncode == 0 and result.stdout == output, (name, front, result)
    assert result.stderr.count('error:') == len(errors), (name, result.stderr)
    for diagnostic in set(errors):
        assert result.stderr.count(diagnostic) == errors.count(diagnostic), (name, result.stderr)


for front in fronts:
    check(front, 'reserved session identity', '''var x=7;
fn __session(){}
var y=9;
x
__session()
fn caller(){__session();}
pub fn __session(){}
extern "C" fn __session();
fn __session[T](){}
x+y''', '7\n16\n',
          ['internal session function cannot be redefined'] * 4 +
          ['internal session function is not callable'] * 2)

    # Each former bump-only session exceeded 65536 slots. A persistent view
    # pins old storage throughout allocation, cleanup and failed submissions.
    start = 'import "std/mem";\nvar a=[2]i64{7,8};\nlet r=&mut a[1];\n'
    blocks = '\n'.join('{var scratch=[512]i64{};scratch[511]=99;}' for _ in range(160))
    check(front, 'temporary arrays', start + blocks + '\n*r=42;\n*r\n:forget r\na[0]+a[1]', '42\n49\n')
    bindings = '\n'.join('var scratch=[512]i64{};\nscratch[511]=99;\n:forget scratch' for _ in range(160))
    check(front, 'forgotten arrays', start + bindings + '\n*r=42;\n*r\n:forget r\na[0]+a[1]', '42\n49\n')

    # Forgetting an interior owner must remove its drop descriptor even though
    # its hole cannot yet be reused. Later reuse stores a non-owner there.
    check(front, 'interior owner descriptor', '''import "std/mem";
var first=new[i64](11);
var middle=new[[2]i64]([2]i64{22,33});
var last=new[i64](44);
let view=&*last;
:forget middle
mem.owner_count()
*view
:forget view
:forget last
var number=77;
number
mem.owner_count()
:forget first
mem.owner_count()''', '2\n44\n77\n1\n0\n')

    owners = '\n'.join('var scratch=[512]own[i64]{};\nscratch[511]=new[i64](99);\n:forget scratch\nvar scalar=123;\n:forget scalar' for _ in range(160))
    check(front, 'owner descriptors and type changes', start + owners + '\n*r\nmem.owner_count()', '8\n0\n')

    # Compile failures must discard descriptors without dropping uninitialized
    # slots. Runtime failures must drop initialized owners and discard new loans.
    failures = '\n'.join('{var scratch=[512]own[i64]{};scratch[511]=new[i64](99);assert(false);}' for _ in range(160))
    check(front, 'runtime rollback storage', start + failures + '\n*r=42;\n*r\nmem.owner_count()',
          '42\n0\n', ['assertion failed'] * 160)
    failures = '\n'.join('let rejected=new[[512]i64]([512]i64{}); extra;' for _ in range(160))
    check(front, 'compile rollback descriptors', start + failures + '\nvar scalar=123;\nscalar\n*r\nmem.owner_count()',
          '123\n8\n0\n', ['one statement per submission'] * 160)

    # Break/continue cleanup emits several instructions sharing one defer
    # argument vector. Cleanup owns the vector once, independently of code paths.
    prefix = 'var total=0;\nlet r=&mut total;\nfn add(p:&mut i64,n:i64){*p=*p+n;}\n'
    deferred = '\n'.join('{var i=0;while(i<3){defer add(r,10);i=i+1;if(i==1){continue;}if(i==2){break;}}}' for _ in range(160))
    check(front, 'shared defer bytecode arguments', prefix + deferred + '\n*r', '3200\n')
    failing = '\n'.join('{{defer add(r,1);}assert(false);}' for _ in range(160))
    check(front, 'unwind compiled argument pools', prefix + failing + '\n*r', '160\n', ['assertion failed'] * 160)
    oversized = '{var scratch=[32720]i64{};' + 'add(r,1);' * 32 + '}'
    check(front, 'rejected generated bytecode is reclaimed', prefix + oversized + '\nadd(r,7);\n*r', '7\n', ['session register limit exceeded'])

    # Accepted calls span zero through the maximum 32 arguments. Owned
    # parameters verify that argument scratch never owns the passed values.
    parameters = ','.join(f'a{i}:own[i64]' for i in range(32))
    expression = '+'.join(f'*a{i}' for i in range(32))
    arguments = ','.join(f'new[i64]({i + 1})' for i in range(32))
    source = 'import "std/mem";\nfn zero()->i64{return 41;}\n'
    source += f'fn many({parameters})->i64{{return {expression};}}\n'
    source += (f'zero()\nmany({arguments})\nmem.owner_count()\n') * 6
    check(front, 'bounded native call scratch and ownership', source, '41\n528\n0\n' * 6)

    check(front, 'deep call recovery releases owners and native scratch',
          'import "std/mem";\nvar survivor=7;\nfn recurse(p:own[i64],n:i64)->i64{return recurse(move p,n+1); }\nrecurse(new[i64](99),0)\nsurvivor\nmem.owner_count()',
          '7\n0\n', ['call depth limit exceeded'])

    # Coercions clone AST nodes. Those copies must enter the same disposable
    # pool without copying its linkage. Generic function AST stays cached.
    source = 'fn identity[T](value:T)->T{return value;}\n'
    source += 'let word="still here";\nvar small:i8=7;\nvar decimal:f32=f32(1.25);\nvar pointer:*i64=null;\n'
    source += ('{let integer:i64=small;let real:f64=decimal;let literal:f64=3;let erased:*void=pointer;assert(integer==7);assert(real==1.25);assert(literal==3.0);assert(erased==null);assert(identity[i64](integer)==7);assert(identity[f64](real)==1.25); }\n') * 160
    source += 'identity[i64](42)\nidentity[f64](2.5)\nword'
    check(front, 'disposable coerced nodes and persistent specializations', source, '42\n2.5\nstill here\n')

    # A surviving slice may remember an intermediate parent whose lexical
    # block has ended. Local reclamation must follow loan identities, too.
    source = 'var a=[1]i64{1};\nvar b=[1]i64{2};\n'
    source += 'var s=a[:];\n{let parent=b[:];s=parent[:];}\n'
    source += '{var churn=7;assert(churn==7);}\n' * 512
    source += 's[0]\nb[0]=9;\n:forget s\nb[0]=5;\nb[0]'
    check(front, 'out-of-scope parent metadata remains live', source, '2\n5\n', ['conflicts'])
    source = source.replace('{let parent=b[:];s=parent[:];}', '{let parent=b[:];s=parent[:];assert(false);}')
    check(front, 'runtime rollback retains new parent identities', source, '2\n5\n', ['assertion failed', 'conflicts'])
    source = 'var survivor=7;\n' + 'var rejected=[32768]i64{};\n' * 160
    source += 'let view=&mut survivor;\n*view=9;\n*view\n:forget view\nsurvivor'
    check(front, 'incomplete local allocation rollback', source, '9\n9\n', ['function storage limit exceeded'] * 160)
    source = 'enum View{None;Some([]i64); }\nvar a=[1]i64{1};\nvar b=[1]i64{4};\nvar s=a[:];\n'
    source += 'match(View.Some(b[:])){View.None=>{} View.Some(part)=>{s=part[:];}}\n'
    source += '{var churn=7;}\n' * 512
    source += 's[0]\n:forget s\nb[0]=7;\nb[0]'
    check(front, 'anonymous match holder and surviving roots', source, '4\n7\n')

    # The restriction belongs to the REPL implementation, not the language's
    # ordinary identifier namespace.
    with tempfile.TemporaryDirectory(prefix='cool-session-name-') as directory:
        source = Path(directory) / 'main.cool'
        source.write_text('import "std/io";fn __session()->i64{return 42;}fn main(){io.println(__session());}')
        result = subprocess.run([*front, 'run', source], text=True, capture_output=True, timeout=30)
        assert (result.returncode, result.stdout, result.stderr) == (0, '42\n', ''), result
print('REPL storage: reserved identity, stable live references, tail reuse, mixed owner types and compile/runtime rollback on all frontends PASS')
